
import type { Product, Category, Banner, Config } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImageUrl = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  return image ? image.imageUrl : 'https://picsum.photos/seed/placeholder/800/800';
}

export const products: Product[] = [
  {
    id: "prod_001",
    nome: "Arroz Tio João",
    descricao: "Arroz branco tipo 1, grãos longos e soltos, perfeito para o dia a dia da sua família.",
    categoria: "graos",
    preco: 28.90,
    precoAntigo: 33.90,
    emPromocao: true,
    imagemURL: getImageUrl("prod_001"),
    imagemThumb: getImageUrl("prod_001"),
    estoque: 45,
    estoqueMinimo: 10,
    unidade: "pacote",
    peso: "5kg",
    marca: "Tio João",
    ativo: true,
    destaque: true,
    ordem: 1,
    tags: ["arroz", "grãos", "básico", "tipo1", "tio joão"],
    vezesVendido: 150,
    variantGroupId: "arroz-tio-joao"
  },
  {
    id: "prod_002",
    nome: "Feijão Camil",
    descricao: "Feijão carioca tipo 1, com grãos macios e saborosos. Indispensável na mesa brasileira.",
    categoria: "graos",
    preco: 8.50,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_002"),
    imagemThumb: getImageUrl("prod_002"),
    estoque: 30,
    estoqueMinimo: 10,
    unidade: "pacote",
    peso: "1kg",
    marca: "Camil",
    ativo: true,
    destaque: true,
    ordem: 2,
    tags: ["feijão", "grãos", "camil", "carioca"],
    vezesVendido: 210
  },
  {
    id: "prod_003",
    nome: "Óleo de Soja Soya",
    descricao: "Óleo de soja refinado, ideal para cozinhar, fritar e temperar.",
    categoria: "mercearia",
    preco: 7.20,
    precoAntigo: 8.00,
    emPromocao: true,
    imagemURL: getImageUrl("prod_003"),
    imagemThumb: getImageUrl("prod_003"),
    estoque: 80,
    estoqueMinimo: 20,
    unidade: "unidade",
    peso: "900ml",
    marca: "Soya",
    ativo: true,
    destaque: false,
    ordem: 3,
    tags: ["oleo", "soja", "cozinha"],
    vezesVendido: 180
  },
  {
    id: "prod_004",
    nome: "Leite UHT Integral Italac",
    descricao: "Leite longa vida integral, rico em cálcio e proteínas.",
    categoria: "laticinios",
    preco: 4.50,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_004"),
    imagemThumb: getImageUrl("prod_004"),
    estoque: 120,
    estoqueMinimo: 30,
    unidade: "caixa",
    peso: "1L",
    marca: "Italac",
    ativo: true,
    destaque: true,
    ordem: 4,
    tags: ["leite", "laticinios", "uht", "integral"],
    vezesVendido: 350
  },
  {
    id: "prod_005",
    nome: "Refrigerante Coca-Cola",
    descricao: "O sabor inconfundível da Coca-Cola para compartilhar com amigos e família.",
    categoria: "bebidas",
    preco: 9.99,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_005"),
    imagemThumb: getImageUrl("prod_005"),
    estoque: 60,
    estoqueMinimo: 15,
    unidade: "garrafa",
    peso: "2L",
    marca: "Coca-Cola",
    ativo: true,
    destaque: true,
    ordem: 5,
    tags: ["refrigerante", "coca-cola", "bebidas", "coke"],
    vezesVendido: 300,
    variantGroupId: "coca-cola",
    variantName: "2L"
  },
  {
    id: "prod_005_1L",
    nome: "Refrigerante Coca-Cola",
    descricao: "O sabor inconfundível da Coca-Cola para compartilhar com amigos e família.",
    categoria: "bebidas",
    preco: 6.99,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_005"),
    imagemThumb: getImageUrl("prod_005"),
    estoque: 40,
    estoqueMinimo: 10,
    unidade: "garrafa",
    peso: "1L",
    marca: "Coca-Cola",
    ativo: true,
    destaque: false,
    ordem: 5,
    tags: ["refrigerante", "coca-cola", "bebidas", "coke"],
    vezesVendido: 150,
    variantGroupId: "coca-cola",
    variantName: "1L"
  },
  {
    id: "prod_005_600ml",
    nome: "Refrigerante Coca-Cola",
    descricao: "O sabor inconfundível da Coca-Cola para compartilhar com amigos e família.",
    categoria: "bebidas",
    preco: 4.50,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_005"),
    imagemThumb: getImageUrl("prod_005"),
    estoque: 80,
    estoqueMinimo: 20,
    unidade: "garrafa",
    peso: "600ml",
    marca: "Coca-Cola",
    ativo: true,
    destaque: false,
    ordem: 5,
    tags: ["refrigerante", "coca-cola", "bebidas", "coke"],
    vezesVendido: 200,
    variantGroupId: "coca-cola",
    variantName: "600ml"
  },
  {
    id: "prod_006",
    nome: "Contra Filé",
    descricao: "Corte nobre de carne bovina, perfeito para churrascos e bifes suculentos.",
    categoria: "carnes",
    preco: 45.90,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_006"),
    imagemThumb: getImageUrl("prod_006"),
    estoque: 15,
    estoqueMinimo: 5,
    unidade: "kg",
    peso: "1kg",
    marca: "Açougue Luzia",
    ativo: true,
    destaque: false,
    ordem: 6,
    tags: ["carne", "bovina", "churrasco", "contra file"],
    vezesVendido: 90
  },
  {
    id: "prod_007",
    nome: "Peito de Frango",
    descricao: "Peito de frango sem osso e sem pele, congelado. Versátil e saudável para suas receitas.",
    categoria: "carnes",
    preco: 18.99,
    precoAntigo: 22.50,
    emPromocao: true,
    imagemURL: getImageUrl("prod_007"),
    imagemThumb: getImageUrl("prod_007"),
    estoque: 25,
    estoqueMinimo: 10,
    unidade: "kg",
    peso: "1kg",
    marca: "Sadia",
    ativo: true,
    destaque: false,
    ordem: 7,
    tags: ["frango", "carne", "aves", "sadia"],
    vezesVendido: 120
  },
  {
    id: "prod_008",
    nome: "Doce de Leite",
    descricao: "Cremoso e delicioso doce de leite, perfeito para sobremesas ou para comer de colher.",
    categoria: "doces",
    preco: 12.50,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_008"),
    imagemThumb: getImageUrl("prod_008"),
    estoque: 40,
    estoqueMinimo: 5,
    unidade: "pote",
    peso: "400g",
    marca: "Viçosa",
    ativo: true,
    destaque: false,
    ordem: 8,
    tags: ["doce", "leite", "sobremesa"],
    vezesVendido: 85
  },
  {
    id: "prod_009",
    nome: "Biscoito Wafer Bauducco Chocolate",
    descricao: "Biscoito wafer crocante com recheio sabor chocolate. Pacote com 140g.",
    categoria: "doces",
    preco: 3.29,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_009"),
    imagemThumb: getImageUrl("prod_009"),
    estoque: 90,
    estoqueMinimo: 20,
    unidade: "pacote",
    peso: "140g",
    marca: "Bauducco",
    ativo: true,
    destaque: false,
    ordem: 9,
    tags: ["biscoito", "wafer", "bauducco", "chocolate", "doce"],
    vezesVendido: 250
  },
  {
    id: "prod_010",
    nome: "Pão Francês",
    descricao: "Pão francês fresquinho, crocante por fora e macio por dentro. Vendido por unidade.",
    categoria: "padaria",
    preco: 0.75,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_010"),
    imagemThumb: getImageUrl("prod_010"),
    estoque: 200,
    estoqueMinimo: 50,
    unidade: "unidade",
    marca: "Padaria Luzia",
    ativo: true,
    destaque: true,
    ordem: 10,
    tags: ["pão", "francês", "padaria"],
    vezesVendido: 500
  },
  {
    id: "prod_011",
    nome: "Lava Roupas em Pó Omo",
    descricao: "Lava roupas com poder de limpeza imbatível para remover as manchas mais difíceis.",
    categoria: "limpeza",
    preco: 15.99,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_011"),
    imagemThumb: getImageUrl("prod_011"),
    estoque: 50,
    estoqueMinimo: 10,
    unidade: "caixa",
    peso: "1kg",
    marca: "Omo",
    ativo: true,
    destaque: false,
    ordem: 11,
    tags: ["limpeza", "sabão", "omo", "lava roupas"],
    vezesVendido: 130
  },
  {
    id: "prod_012",
    nome: "Maçã Fuji",
    descricao: "Maçãs Fuji frescas e crocantes, doces e suculentas.",
    categoria: "hortifruti",
    preco: 9.98,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_012"),
    imagemThumb: getImageUrl("prod_012"),
    estoque: 35,
    estoqueMinimo: 10,
    unidade: "kg",
    peso: "1kg",
    marca: "Hortifruti Luzia",
    ativo: true,
    destaque: false,
    ordem: 12,
    tags: ["fruta", "maçã", "fuji", "hortifruti"],
    vezesVendido: 95
  },
  {
    id: "prod_013",
    nome: "Banana Prata",
    descricao: "Banana prata madura, ideal para consumo in natura ou em vitaminas.",
    categoria: "hortifruti",
    preco: 5.49,
    precoAntigo: null,
    emPromocao: false,
    imagemURL: getImageUrl("prod_013"),
    imagemThumb: getImageUrl("prod_013"),
    estoque: 0,
    estoqueMinimo: 10,
    unidade: "kg",
    peso: "1kg",
    marca: "Hortifruti Luzia",
    ativo: true,
    destaque: false,
    ordem: 13,
    tags: ["fruta", "banana", "prata", "hortifruti"],
    vezesVendido: 140
  },
  {
    id: "prod_014",
    nome: "Água Mineral",
    descricao: "Água mineral sem gás, fonte de hidratação.",
    categoria: "bebidas",
    preco: 2.50,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_014"), imagemThumb: getImageUrl("prod_014"),
    estoque: 150, estoqueMinimo: 30, unidade: "unidade", peso: "500ml", marca: "Indaiá",
    ativo: true, destaque: false, ordem: 14, tags: ["bebidas", "água"], vezesVendido: 200
  },
  {
    id: "prod_015",
    nome: "Cerveja Heineken",
    descricao: "Cerveja premium lager, puro malte.",
    categoria: "bebidas",
    preco: 5.99,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_015"), imagemThumb: getImageUrl("prod_015"),
    estoque: 70, estoqueMinimo: 20, unidade: "unidade", peso: "330ml", marca: "Heineken",
    ativo: true, destaque: false, ordem: 15, tags: ["bebidas", "cerveja"], vezesVendido: 180
  },
  {
    id: "prod_016",
    nome: "Queijo Mussarela",
    descricao: "Queijo mussarela fatiado, ideal para sanduíches e pizzas.",
    categoria: "laticinios",
    preco: 12.00,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_016"), imagemThumb: getImageUrl("prod_016"),
    estoque: 40, estoqueMinimo: 10, unidade: "pacote", peso: "200g", marca: "Sadia",
    ativo: true, destaque: false, ordem: 16, tags: ["laticinios", "frios", "queijo"], vezesVendido: 150
  },
  {
    id: "prod_017",
    nome: "Iogurte Natural",
    descricao: "Iogurte natural desnatado, sem adição de açúcar.",
    categoria: "laticinios",
    preco: 3.80,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_017"), imagemThumb: getImageUrl("prod_017"),
    estoque: 60, estoqueMinimo: 15, unidade: "unidade", peso: "170g", marca: "Danone",
    ativo: true, destaque: false, ordem: 17, tags: ["laticinios", "iogurte"], vezesVendido: 110
  },
  {
    id: "prod_018",
    nome: "Detergente Ypê",
    descricao: "Detergente líquido neutro, alto poder desengordurante.",
    categoria: "limpeza",
    preco: 2.99,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_018"), imagemThumb: getImageUrl("prod_018"),
    estoque: 100, estoqueMinimo: 20, unidade: "unidade", peso: "500ml", marca: "Ypê",
    ativo: true, destaque: false, ordem: 18, tags: ["limpeza", "detergente"], vezesVendido: 220
  },
  {
    id: "prod_019",
    nome: "Água Sanitária",
    descricao: "Água sanitária com cloro ativo, para limpeza e desinfecção.",
    categoria: "limpeza",
    preco: 4.20,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_019"), imagemThumb: getImageUrl("prod_019"),
    estoque: 80, estoqueMinimo: 15, unidade: "unidade", peso: "1L", marca: "Qboa",
    ativo: true, destaque: false, ordem: 19, tags: ["limpeza", "água sanitária"], vezesVendido: 140
  },
  {
    id: "prod_020",
    nome: "Pão de Forma Pullman",
    descricao: "Pão de forma tradicional, macio e saboroso.",
    categoria: "padaria",
    preco: 8.90,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_020"), imagemThumb: getImageUrl("prod_020"),
    estoque: 40, estoqueMinimo: 10, unidade: "pacote", peso: "480g", marca: "Pullman",
    ativo: true, destaque: false, ordem: 20, tags: ["padaria", "pão"], vezesVendido: 160
  },
  {
    id: "prod_021",
    nome: "Bolo de Chocolate",
    descricao: "Bolo de chocolate fofinho com cobertura.",
    categoria: "padaria",
    preco: 15.00,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_021"), imagemThumb: getImageUrl("prod_021"),
    estoque: 20, estoqueMinimo: 5, unidade: "unidade", peso: "300g", marca: "Padaria Luzia",
    ativo: true, destaque: false, ordem: 21, tags: ["padaria", "bolo"], vezesVendido: 80
  },
  {
    id: "prod_022",
    nome: "Tomate",
    descricao: "Tomates frescos e maduros, perfeitos para saladas e molhos.",
    categoria: "hortifruti",
    preco: 8.50,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_022"), imagemThumb: getImageUrl("prod_022"),
    estoque: 30, estoqueMinimo: 8, unidade: "kg", peso: "1kg", marca: "Hortifruti Luzia",
    ativo: true, destaque: false, ordem: 22, tags: ["hortifruti", "tomate"], vezesVendido: 100
  },
  {
    id: "prod_023",
    nome: "Alface Crespa",
    descricao: "Alface crespa fresca e crocante.",
    categoria: "hortifruti",
    preco: 3.50,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_023"), imagemThumb: getImageUrl("prod_023"),
    estoque: 50, estoqueMinimo: 10, unidade: "unidade", marca: "Hortifruti Luzia",
    ativo: true, destaque: false, ordem: 23, tags: ["hortifruti", "alface"], vezesVendido: 120
  },
  {
    id: "prod_024",
    nome: "Chocolate Lacta",
    descricao: "Barra de chocolate ao leite Lacta.",
    categoria: "doces",
    preco: 6.99,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_024"), imagemThumb: getImageUrl("prod_024"),
    estoque: 100, estoqueMinimo: 20, unidade: "unidade", peso: "90g", marca: "Lacta",
    ativo: true, destaque: false, ordem: 24, tags: ["doces", "chocolate"], vezesVendido: 280
  },
  {
    id: "prod_025",
    nome: "Biscoito Maizena",
    descricao: "Biscoito de maizena, ideal para acompanhar um café.",
    categoria: "doces",
    preco: 4.00,
    precoAntigo: null, emPromocao: false,
    imagemURL: getImageUrl("prod_025"), imagemThumb: getImageUrl("prod_025"),
    estoque: 80, estoqueMinimo: 15, unidade: "pacote", peso: "170g", marca: "Piraquê",
    ativo: true, destaque: false, ordem: 25, tags: ["doces", "biscoito"], vezesVendido: 190
  },
  // Novos produtos - Grãos e Cereais
  { id: "prod_026", nome: "Arroz Integral Tio João", descricao: "Arroz integral, fonte de fibras.", categoria: "graos", preco: 10.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_026"), imagemThumb: getImageUrl("prod_026"), estoque: 30, estoqueMinimo: 5, unidade: "pacote", peso: "1kg", marca: "Tio João", ativo: true, destaque: false, ordem: 26, tags: ["arroz", "integral", "grãos"], vezesVendido: 50, variantGroupId: "arroz-tio-joao" },
  { id: "prod_027", nome: "Feijão Preto Kicaldo", descricao: "Feijão preto ideal para feijoada.", categoria: "graos", preco: 9.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_027"), imagemThumb: getImageUrl("prod_027"), estoque: 40, estoqueMinimo: 10, unidade: "pacote", peso: "1kg", marca: "Kicaldo", ativo: true, destaque: false, ordem: 27, tags: ["feijão", "preto", "grãos"], vezesVendido: 80 },
  { id: "prod_028", nome: "Aveia em Flocos Quaker", descricao: "Aveia em flocos para um café da manhã saudável.", categoria: "graos", preco: 12.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_028"), imagemThumb: getImageUrl("prod_028"), estoque: 50, estoqueMinimo: 10, unidade: "caixa", peso: "500g", marca: "Quaker", ativo: true, destaque: false, ordem: 28, tags: ["aveia", "cereal", "grãos"], vezesVendido: 110 },
  { id: "prod_029", nome: "Milho para Pipoca Yoki", descricao: "Milho de pipoca para uma sessão de cinema em casa.", categoria: "graos", preco: 5.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_029"), imagemThumb: getImageUrl("prod_029"), estoque: 60, estoqueMinimo: 15, unidade: "pacote", peso: "500g", marca: "Yoki", ativo: true, destaque: false, ordem: 29, tags: ["pipoca", "milho", "grãos"], vezesVendido: 130 },
  { id: "prod_030", nome: "Lentilha Kicaldo", descricao: "Lentilha para sopas e saladas.", categoria: "graos", preco: 8.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_030"), imagemThumb: getImageUrl("prod_030"), estoque: 25, estoqueMinimo: 5, unidade: "pacote", peso: "500g", marca: "Kicaldo", ativo: true, destaque: false, ordem: 30, tags: ["lentilha", "grãos"], vezesVendido: 40 },
  { id: "prod_031", nome: "Farinha de Trigo Dona Benta", descricao: "Farinha de trigo tipo 1 para pães e bolos.", categoria: "graos", preco: 6.20, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_031"), imagemThumb: getImageUrl("prod_031"), estoque: 70, estoqueMinimo: 20, unidade: "pacote", peso: "1kg", marca: "Dona Benta", ativo: true, destaque: false, ordem: 31, tags: ["farinha", "trigo"], vezesVendido: 200 },
  { id: "prod_032", nome: "Açúcar Refinado União", descricao: "Açúcar refinado para adoçar suas receitas.", categoria: "graos", preco: 5.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_032"), imagemThumb: getImageUrl("prod_032"), estoque: 100, estoqueMinimo: 25, unidade: "pacote", peso: "1kg", marca: "União", ativo: true, destaque: false, ordem: 32, tags: ["açúcar", "refinado"], vezesVendido: 300 },
  { id: "prod_033", nome: "Fubá Mimoso Yoki", descricao: "Fubá mimoso para polenta e bolos.", categoria: "graos", preco: 4.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_033"), imagemThumb: getImageUrl("prod_033"), estoque: 40, estoqueMinimo: 10, unidade: "pacote", peso: "500g", marca: "Yoki", ativo: true, destaque: false, ordem: 33, tags: ["fubá", "milho"], vezesVendido: 90 },
  { id: "prod_034", nome: "Quinoa em Grãos", descricao: "Quinoa, um superalimento rico em proteínas.", categoria: "graos", preco: 15.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_034"), imagemThumb: getImageUrl("prod_034"), estoque: 20, estoqueMinimo: 5, unidade: "pacote", peso: "250g", marca: "Mãe Terra", ativo: true, destaque: false, ordem: 34, tags: ["quinoa", "grãos", "saudável"], vezesVendido: 30 },
  { id: "prod_035", nome: "Cereal Matinal Nescau", descricao: "Cereal de milho com chocolate.", categoria: "graos", preco: 14.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_035"), imagemThumb: getImageUrl("prod_035"), estoque: 35, estoqueMinimo: 10, unidade: "caixa", peso: "270g", marca: "Nescau", ativo: true, destaque: false, ordem: 35, tags: ["cereal", "nescau"], vezesVendido: 100 },
  { id: "prod_036", nome: "Sal Grosso Cisne", descricao: "Sal grosso para churrasco.", categoria: "graos", preco: 3.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_036"), imagemThumb: getImageUrl("prod_036"), estoque: 50, estoqueMinimo: 10, unidade: "pacote", peso: "1kg", marca: "Cisne", ativo: true, destaque: false, ordem: 36, tags: ["sal", "churrasco"], vezesVendido: 70 },
  { id: "prod_037", nome: "Arroz Parboilizado Camil", descricao: "Arroz parboilizado, sempre soltinho.", categoria: "graos", preco: 7.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_037"), imagemThumb: getImageUrl("prod_037"), estoque: 40, estoqueMinimo: 10, unidade: "pacote", peso: "1kg", marca: "Camil", ativo: true, destaque: false, ordem: 37, tags: ["arroz", "parboilizado", "grãos"], vezesVendido: 60 },
  { id: "prod_038", nome: "Ervilha em Conserva", descricao: "Ervilhas selecionadas em conserva.", categoria: "graos", preco: 4.20, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_038"), imagemThumb: getImageUrl("prod_038"), estoque: 60, estoqueMinimo: 15, unidade: "lata", peso: "200g", marca: "Quero", ativo: true, destaque: false, ordem: 38, tags: ["ervilha", "conserva"], vezesVendido: 85 },
  { id: "prod_039", nome: "Grão de Bico Kicaldo", descricao: "Grão de bico para saladas e pastas.", categoria: "graos", preco: 9.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_039"), imagemThumb: getImageUrl("prod_039"), estoque: 25, estoqueMinimo: 5, unidade: "pacote", peso: "500g", marca: "Kicaldo", ativo: true, destaque: false, ordem: 39, tags: ["grão de bico", "grãos"], vezesVendido: 35 },
  { id: "prod_040", nome: "Trigo para Kibe Yoki", descricao: "Trigo para o preparo de kibe.", categoria: "graos", preco: 7.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_040"), imagemThumb: getImageUrl("prod_040"), estoque: 30, estoqueMinimo: 5, unidade: "pacote", peso: "500g", marca: "Yoki", ativo: true, destaque: false, ordem: 40, tags: ["trigo", "kibe", "grãos"], vezesVendido: 45 },

  // Novos produtos - Carnes e Aves
  { id: "prod_041", nome: "Picanha Bovina", descricao: "Picanha, o corte mais nobre para churrasco.", categoria: "carnes", preco: 79.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_041"), imagemThumb: getImageUrl("prod_041"), estoque: 10, estoqueMinimo: 3, unidade: "kg", peso: "1kg", marca: "Friboi", ativo: true, destaque: true, ordem: 41, tags: ["carne", "picanha", "churrasco"], vezesVendido: 50 },
  { id: "prod_042", nome: "Linguiça Toscana Sadia", descricao: "Linguiça toscana de porco para churrasco.", categoria: "carnes", preco: 25.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_042"), imagemThumb: getImageUrl("prod_042"), estoque: 30, estoqueMinimo: 8, unidade: "kg", peso: "1kg", marca: "Sadia", ativo: true, destaque: false, ordem: 42, tags: ["linguiça", "porco", "churrasco"], vezesVendido: 100 },
  { id: "prod_043", nome: "Asa de Frango", descricao: "Asinhas de frango para petiscos.", categoria: "carnes", preco: 15.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_043"), imagemThumb: getImageUrl("prod_043"), estoque: 40, estoqueMinimo: 10, unidade: "kg", peso: "1kg", marca: "Perdigão", ativo: true, destaque: false, ordem: 43, tags: ["frango", "asa", "petisco"], vezesVendido: 110 },
  { id: "prod_044", nome: "Carne Moída Patinho", descricao: "Carne moída de patinho, magra e saborosa.", categoria: "carnes", preco: 22.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_044"), imagemThumb: getImageUrl("prod_044"), estoque: 25, estoqueMinimo: 5, unidade: "pacote", peso: "500g", marca: "Açougue Luzia", ativo: true, destaque: false, ordem: 44, tags: ["carne", "moída", "patinho"], vezesVendido: 150 },
  { id: "prod_045", nome: "Costela Bovina", descricao: "Costela bovina para assados e cozidos.", categoria: "carnes", preco: 35.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_045"), imagemThumb: getImageUrl("prod_045"), estoque: 15, estoqueMinimo: 4, unidade: "kg", peso: "1kg", marca: "Friboi", ativo: true, destaque: false, ordem: 45, tags: ["carne", "costela", "assado"], vezesVendido: 70 },
  { id: "prod_046", nome: "Bisteca Suína", descricao: "Bistecas de porco para fritar ou grelhar.", categoria: "carnes", preco: 28.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_046"), imagemThumb: getImageUrl("prod_046"), estoque: 20, estoqueMinimo: 5, unidade: "kg", peso: "1kg", marca: "Açougue Luzia", ativo: true, destaque: false, ordem: 46, tags: ["carne", "suína", "bisteca"], vezesVendido: 80 },
  { id: "prod_047", nome: "Filé de Tilápia", descricao: "Filés de tilápia congelados e sem espinhas.", categoria: "carnes", preco: 32.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_047"), imagemThumb: getImageUrl("prod_047"), estoque: 18, estoqueMinimo: 5, unidade: "pacote", peso: "500g", marca: "Copacol", ativo: true, destaque: false, ordem: 47, tags: ["peixe", "tilápia", "filé"], vezesVendido: 60 },
  { id: "prod_048", nome: "Coração de Frango", descricao: "Coração de frango para churrasco.", categoria: "carnes", preco: 25.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_048"), imagemThumb: getImageUrl("prod_048"), estoque: 22, estoqueMinimo: 6, unidade: "kg", peso: "1kg", marca: "Sadia", ativo: true, destaque: false, ordem: 48, tags: ["frango", "coração", "churrasco"], vezesVendido: 95 },
  { id: "prod_049", nome: "Alcatra Bovina", descricao: "Alcatra, corte macio para bifes e assados.", categoria: "carnes", preco: 49.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_049"), imagemThumb: getImageUrl("prod_049"), estoque: 12, estoqueMinimo: 3, unidade: "kg", peso: "1kg", marca: "Friboi", ativo: true, destaque: false, ordem: 49, tags: ["carne", "alcatra", "bife"], vezesVendido: 55 },
  { id: "prod_050", nome: "Hambúrguer de Carne", descricao: "Hambúrgueres de carne bovina congelados.", categoria: "carnes", preco: 29.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_050"), imagemThumb: getImageUrl("prod_050"), estoque: 30, estoqueMinimo: 10, unidade: "caixa", peso: "12un", marca: "Sadia", ativo: true, destaque: false, ordem: 50, tags: ["hambúrguer", "carne", "lanche"], vezesVendido: 130 },
  { id: "prod_051", nome: "Bacon em Fatias", descricao: "Bacon suíno fatiado para dar sabor a tudo.", categoria: "carnes", preco: 15.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_051"), imagemThumb: getImageUrl("prod_051"), estoque: 40, estoqueMinimo: 10, unidade: "pacote", peso: "200g", marca: "Perdigão", ativo: true, destaque: false, ordem: 51, tags: ["bacon", "suíno", "frios"], vezesVendido: 180 },
  { id: "prod_052", nome: "Salsicha Hot Dog Perdigão", descricao: "Salsichas para cachorro-quente.", categoria: "carnes", preco: 11.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_052"), imagemThumb: getImageUrl("prod_052"), estoque: 50, estoqueMinimo: 15, unidade: "pacote", peso: "500g", marca: "Perdigão", ativo: true, destaque: false, ordem: 52, tags: ["salsicha", "hot dog", "frios"], vezesVendido: 140 },
  { id: "prod_053", nome: "Coxa e Sobrecoxa de Frango", descricao: "Cortes de frango com osso.", categoria: "carnes", preco: 14.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_053"), imagemThumb: getImageUrl("prod_053"), estoque: 35, estoqueMinimo: 10, unidade: "kg", peso: "1kg", marca: "Aurora", ativo: true, destaque: false, ordem: 53, tags: ["frango", "coxa", "sobrecoxa"], vezesVendido: 105 },
  { id: "prod_054", nome: "Cupim Bovino", descricao: "Cupim, ideal para assados longos.", categoria: "carnes", preco: 42.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_054"), imagemThumb: getImageUrl("prod_054"), estoque: 10, estoqueMinimo: 2, unidade: "kg", peso: "1kg", marca: "Açougue Luzia", ativo: true, destaque: false, ordem: 54, tags: ["carne", "cupim", "assado"], vezesVendido: 40 },
  { id: "prod_055", nome: "Mortadela Defumada Sadia", descricao: "Mortadela defumada e fatiada.", categoria: "carnes", preco: 8.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_055"), imagemThumb: getImageUrl("prod_055"), estoque: 30, estoqueMinimo: 5, unidade: "pacote", peso: "200g", marca: "Sadia", ativo: true, destaque: false, ordem: 55, tags: ["mortadela", "frios", "defumado"], vezesVendido: 120 },

  // Novos produtos - Laticínios e Frios
  { id: "prod_056", nome: "Presunto Cozido Sadia", descricao: "Presunto cozido fatiado.", categoria: "laticinios", preco: 10.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_056"), imagemThumb: getImageUrl("prod_056"), estoque: 45, estoqueMinimo: 10, unidade: "pacote", peso: "200g", marca: "Sadia", ativo: true, destaque: false, ordem: 56, tags: ["presunto", "frios"], vezesVendido: 160 },
  { id: "prod_057", nome: "Requeijão Cremoso Vigor", descricao: "Requeijão cremoso tradicional.", categoria: "laticinios", preco: 8.70, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_057"), imagemThumb: getImageUrl("prod_057"), estoque: 50, estoqueMinimo: 15, unidade: "copo", peso: "200g", marca: "Vigor", ativo: true, destaque: false, ordem: 57, tags: ["requeijão", "laticinios"], vezesVendido: 200 },
  { id: "prod_058", nome: "Manteiga com Sal Aviação", descricao: "Manteiga de primeira qualidade com sal.", categoria: "laticinios", preco: 13.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_058"), imagemThumb: getImageUrl("prod_058"), estoque: 30, estoqueMinimo: 8, unidade: "pote", peso: "200g", marca: "Aviação", ativo: true, destaque: false, ordem: 58, tags: ["manteiga", "laticinios"], vezesVendido: 180 },
  { id: "prod_059", nome: "Queijo Minas Frescal", descricao: "Queijo minas frescal, leve e saboroso.", categoria: "laticinios", preco: 25.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_059"), imagemThumb: getImageUrl("prod_059"), estoque: 20, estoqueMinimo: 5, unidade: "unidade", peso: "500g", marca: "Tirolez", ativo: true, destaque: false, ordem: 59, tags: ["queijo", "minas", "frescal"], vezesVendido: 90 },
  { id: "prod_060", nome: "Leite Fermentado Yakult", descricao: "Leite fermentado com lactobacilos vivos.", categoria: "laticinios", preco: 9.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_060"), imagemThumb: getImageUrl("prod_060"), estoque: 40, estoqueMinimo: 10, unidade: "pack", peso: "6un", marca: "Yakult", ativo: true, destaque: false, ordem: 60, tags: ["leite", "fermentado", "yakult"], vezesVendido: 150 },
  { id: "prod_061", nome: "Creme de Leite UHT Nestlé", descricao: "Creme de leite para receitas doces e salgadas.", categoria: "laticinios", preco: 4.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_061"), imagemThumb: getImageUrl("prod_061"), estoque: 80, estoqueMinimo: 20, unidade: "caixa", peso: "200g", marca: "Nestlé", ativo: true, destaque: false, ordem: 61, tags: ["creme de leite", "laticinios"], vezesVendido: 250 },
  { id: "prod_062", nome: "Iogurte Grego Vigor", descricao: "Iogurte grego, cremosidade inigualável.", categoria: "laticinios", preco: 4.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_062"), imagemThumb: getImageUrl("prod_062"), estoque: 60, estoqueMinimo: 15, unidade: "unidade", peso: "100g", marca: "Vigor", ativo: true, destaque: false, ordem: 62, tags: ["iogurte", "grego", "laticinios"], vezesVendido: 120 },
  { id: "prod_063", nome: "Queijo Parmesão Ralado", descricao: "Queijo parmesão ralado para massas.", categoria: "laticinios", preco: 7.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_063"), imagemThumb: getImageUrl("prod_063"), estoque: 70, estoqueMinimo: 20, unidade: "pacote", peso: "50g", marca: "Vigor", ativo: true, destaque: false, ordem: 63, tags: ["queijo", "parmesão", "ralado"], vezesVendido: 220 },
  { id: "prod_064", nome: "Leite Condensado Moça", descricao: "Leite condensado para sobremesas.", categoria: "laticinios", preco: 8.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_064"), imagemThumb: getImageUrl("prod_064"), estoque: 90, estoqueMinimo: 25, unidade: "lata", peso: "395g", marca: "Moça", ativo: true, destaque: false, ordem: 64, tags: ["leite condensado", "doce"], vezesVendido: 350 },
  { id: "prod_065", nome: "Ovos Brancos", descricao: "Dúzia de ovos brancos tipo grande.", categoria: "laticinios", preco: 12.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_065"), imagemThumb: getImageUrl("prod_065"), estoque: 50, estoqueMinimo: 15, unidade: "dúzia", peso: "12un", marca: "Granja Feliz", ativo: true, destaque: false, ordem: 65, tags: ["ovos", "básicos"], vezesVendido: 280 },
  { id: "prod_066", nome: "Ricota Fresca", descricao: "Ricota fresca, ideal para patês e recheios.", categoria: "laticinios", preco: 9.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_066"), imagemThumb: getImageUrl("prod_066"), estoque: 25, estoqueMinimo: 5, unidade: "unidade", peso: "250g", marca: "Tirolez", ativo: true, destaque: false, ordem: 66, tags: ["ricota", "queijo", "light"], vezesVendido: 70 },
  { id: "prod_067", nome: "Margarina com Sal Qualy", descricao: "Margarina cremosa com sal.", categoria: "laticinios", preco: 7.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_067"), imagemThumb: getImageUrl("prod_067"), estoque: 70, estoqueMinimo: 20, unidade: "pote", peso: "500g", marca: "Qualy", ativo: true, destaque: false, ordem: 67, tags: ["margarina", "qualy"], vezesVendido: 240 },
  { id: "prod_068", nome: "Queijo Coalho", descricao: "Queijo coalho para assar ou grelhar.", categoria: "laticinios", preco: 18.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_068"), imagemThumb: getImageUrl("prod_068"), estoque: 20, estoqueMinimo: 5, unidade: "pacote", peso: "300g", marca: "Sertanorte", ativo: true, destaque: false, ordem: 68, tags: ["queijo", "coalho", "churrasco"], vezesVendido: 100 },
  { id: "prod_069", nome: "Peito de Peru Defumado", descricao: "Peito de peru defumado e fatiado.", categoria: "laticinios", preco: 14.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_069"), imagemThumb: getImageUrl("prod_069"), estoque: 30, estoqueMinimo: 8, unidade: "pacote", peso: "200g", marca: "Sadia", ativo: true, destaque: false, ordem: 69, tags: ["peito de peru", "frios", "light"], vezesVendido: 130 },
  { id: "prod_070", nome: "Leite de Coco Sococo", descricao: "Leite de coco para receitas.", categoria: "laticinios", preco: 5.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_070"), imagemThumb: getImageUrl("prod_070"), estoque: 60, estoqueMinimo: 15, unidade: "garrafa", peso: "200ml", marca: "Sococo", ativo: true, destaque: false, ordem: 70, tags: ["leite de coco", "receitas"], vezesVendido: 110 },

  // Novos produtos - Padaria
  { id: "prod_071", nome: "Pão de Queijo", descricao: "Pão de queijo congelado para assar.", categoria: "padaria", preco: 12.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_071"), imagemThumb: getImageUrl("prod_071"), estoque: 30, estoqueMinimo: 8, unidade: "pacote", peso: "400g", marca: "Forno de Minas", ativo: true, destaque: false, ordem: 71, tags: ["pão de queijo", "padaria"], vezesVendido: 140 },
  { id: "prod_072", nome: "Croissant de Manteiga", descricao: "Croissant amanteigado e folhado.", categoria: "padaria", preco: 5.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_072"), imagemThumb: getImageUrl("prod_072"), estoque: 40, estoqueMinimo: 10, unidade: "unidade", marca: "Padaria Luzia", ativo: true, destaque: false, ordem: 72, tags: ["croissant", "padaria"], vezesVendido: 90 },
  { id: "prod_073", nome: "Torrada Integral Bauducco", descricao: "Torradas integrais, leves e crocantes.", categoria: "padaria", preco: 5.20, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_073"), imagemThumb: getImageUrl("prod_073"), estoque: 50, estoqueMinimo: 15, unidade: "pacote", peso: "142g", marca: "Bauducco", ativo: true, destaque: false, ordem: 73, tags: ["torrada", "integral", "padaria"], vezesVendido: 110 },
  { id: "prod_074", nome: "Baguete", descricao: "Baguete de fermentação natural.", categoria: "padaria", preco: 7.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_074"), imagemThumb: getImageUrl("prod_074"), estoque: 25, estoqueMinimo: 5, unidade: "unidade", marca: "Padaria Luzia", ativo: true, destaque: false, ordem: 74, tags: ["pão", "baguete", "padaria"], vezesVendido: 70 },
  { id: "prod_075", nome: "Sonho de Creme", descricao: "Sonho recheado com creme de confeiteiro.", categoria: "padaria", preco: 4.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_075"), imagemThumb: getImageUrl("prod_075"), estoque: 35, estoqueMinimo: 10, unidade: "unidade", marca: "Padaria Luzia", ativo: true, destaque: false, ordem: 75, tags: ["sonho", "doce", "padaria"], vezesVendido: 120 },
  { id: "prod_076", nome: "Bisnaguinha Pullman", descricao: "Pão tipo bisnaguinha, ideal para lanches.", categoria: "padaria", preco: 7.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_076"), imagemThumb: getImageUrl("prod_076"), estoque: 40, estoqueMinimo: 10, unidade: "pacote", peso: "300g", marca: "Pullman", ativo: true, destaque: false, ordem: 76, tags: ["pão", "bisnaguinha", "lanche"], vezesVendido: 160 },
  { id: "prod_077", nome: "Pão de Hambúrguer", descricao: "Pães de hambúrguer com gergelim.", categoria: "padaria", preco: 6.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_077"), imagemThumb: getImageUrl("prod_077"), estoque: 30, estoqueMinimo: 8, unidade: "pacote", peso: "4un", marca: "Wickbold", ativo: true, destaque: false, ordem: 77, tags: ["pão", "hambúrguer"], vezesVendido: 100 },
  { id: "prod_078", nome: "Broa de Milho", descricao: "Broa de milho fofinha.", categoria: "padaria", preco: 3.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_078"), imagemThumb: getImageUrl("prod_078"), estoque: 25, estoqueMinimo: 5, unidade: "unidade", marca: "Padaria Luzia", ativo: true, destaque: false, ordem: 78, tags: ["broa", "milho", "padaria"], vezesVendido: 80 },
  { id: "prod_079", nome: "Pão Sírio", descricao: "Pão sírio para lanches árabes.", categoria: "padaria", preco: 9.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_079"), imagemThumb: getImageUrl("prod_079"), estoque: 20, estoqueMinimo: 5, unidade: "pacote", peso: "10un", marca: "Pita Bread", ativo: true, destaque: false, ordem: 79, tags: ["pão", "sírio", "árabe"], vezesVendido: 60 },
  { id: "prod_080", nome: "Massa de Pizza", descricao: "Massa de pizza pré-assada.", categoria: "padaria", preco: 8.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_080"), imagemThumb: getImageUrl("prod_080"), estoque: 30, estoqueMinimo: 8, unidade: "unidade", peso: "300g", marca: "Massa Leve", ativo: true, destaque: false, ordem: 80, tags: ["pizza", "massa", "padaria"], vezesVendido: 90 },
  { id: "prod_081", nome: "Rosca Doce", descricao: "Rosca doce com coco ralado.", categoria: "padaria", preco: 10.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_081"), imagemThumb: getImageUrl("prod_081"), estoque: 20, estoqueMinimo: 5, unidade: "unidade", marca: "Padaria Luzia", ativo: true, destaque: false, ordem: 81, tags: ["rosca", "doce", "padaria"], vezesVendido: 75 },
  { id: "prod_082", nome: "Mini Pizza Calabresa", descricao: "Mini pizza congelada de calabresa.", categoria: "padaria", preco: 6.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_082"), imagemThumb: getImageUrl("prod_082"), estoque: 40, estoqueMinimo: 10, unidade: "unidade", marca: "Sadia", ativo: true, destaque: false, ordem: 82, tags: ["pizza", "lanche", "padaria"], vezesVendido: 130 },
  { id: "prod_083", nome: "Pão de Alho", descricao: "Pão de alho para churrasco.", categoria: "padaria", preco: 9.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_083"), imagemThumb: getImageUrl("prod_083"), estoque: 30, estoqueMinimo: 8, unidade: "pacote", peso: "300g", marca: "Santa Massa", ativo: true, destaque: false, ordem: 83, tags: ["pão", "alho", "churrasco"], vezesVendido: 110 },
  { id: "prod_084", nome: "Carolina de Doce de Leite", descricao: "Carolina recheada com doce de leite.", categoria: "padaria", preco: 2.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_084"), imagemThumb: getImageUrl("prod_084"), estoque: 50, estoqueMinimo: 15, unidade: "unidade", marca: "Padaria Luzia", ativo: true, destaque: false, ordem: 84, tags: ["carolina", "doce", "padaria"], vezesVendido: 140 },
  { id: "prod_085", nome: "Misto Quente", descricao: "Sanduíche de presunto e queijo na chapa.", categoria: "padaria", preco: 7.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_085"), imagemThumb: getImageUrl("prod_085"), estoque: 100, estoqueMinimo: 0, unidade: "unidade", marca: "Padaria Luzia", ativo: true, destaque: false, ordem: 85, tags: ["misto", "lanche", "padaria"], vezesVendido: 180 },

  // Novos produtos - Hortifruti
  { id: "prod_086", nome: "Cebola", descricao: "Cebola, tempero essencial na cozinha.", categoria: "hortifruti", preco: 6.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_086"), imagemThumb: getImageUrl("prod_086"), estoque: 40, estoqueMinimo: 10, unidade: "kg", peso: "1kg", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 86, tags: ["cebola", "tempero", "hortifruti"], vezesVendido: 150 },
  { id: "prod_087", nome: "Batata Inglesa", descricao: "Batata para fritar, cozinhar ou assar.", categoria: "hortifruti", preco: 7.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_087"), imagemThumb: getImageUrl("prod_087"), estoque: 50, estoqueMinimo: 15, unidade: "kg", peso: "1kg", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 87, tags: ["batata", "hortifruti"], vezesVendido: 200 },
  { id: "prod_088", nome: "Cenoura", descricao: "Cenouras frescas para saladas e bolos.", categoria: "hortifruti", preco: 5.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_088"), imagemThumb: getImageUrl("prod_088"), estoque: 35, estoqueMinimo: 8, unidade: "kg", peso: "1kg", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 88, tags: ["cenoura", "legume", "hortifruti"], vezesVendido: 130 },
  { id: "prod_089", nome: "Limão Tahiti", descricao: "Limão tahiti, ótimo para sucos e temperos.", categoria: "hortifruti", preco: 4.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_089"), imagemThumb: getImageUrl("prod_089"), estoque: 60, estoqueMinimo: 15, unidade: "kg", peso: "1kg", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 89, tags: ["limão", "fruta", "hortifruti"], vezesVendido: 180 },
  { id: "prod_090", nome: "Abacate", descricao: "Abacate maduro para vitaminas e guacamole.", categoria: "hortifruti", preco: 4.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_090"), imagemThumb: getImageUrl("prod_090"), estoque: 30, estoqueMinimo: 5, unidade: "unidade", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 90, tags: ["abacate", "fruta", "hortifruti"], vezesVendido: 90 },
  { id: "prod_091", nome: "Mamão Formosa", descricao: "Mamão formosa doce e maduro.", categoria: "hortifruti", preco: 7.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_091"), imagemThumb: getImageUrl("prod_091"), estoque: 25, estoqueMinimo: 5, unidade: "unidade", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 91, tags: ["mamão", "fruta", "hortifruti"], vezesVendido: 110 },
  { id: "prod_092", nome: "Alho", descricao: "Cabeças de alho para temperar.", categoria: "hortifruti", preco: 3.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_092"), imagemThumb: getImageUrl("prod_092"), estoque: 70, estoqueMinimo: 20, unidade: "pacote", peso: "100g", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 92, tags: ["alho", "tempero", "hortifruti"], vezesVendido: 250 },
  { id: "prod_093", nome: "Pimentão Verde", descricao: "Pimentão verde para receitas.", categoria: "hortifruti", preco: 2.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_093"), imagemThumb: getImageUrl("prod_093"), estoque: 40, estoqueMinimo: 10, unidade: "unidade", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 93, tags: ["pimentão", "legume", "hortifruti"], vezesVendido: 100 },
  { id: "prod_094", nome: "Brócolis", descricao: "Brócolis ninja fresco.", categoria: "hortifruti", preco: 6.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_094"), imagemThumb: getImageUrl("prod_094"), estoque: 20, estoqueMinimo: 5, unidade: "unidade", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 94, tags: ["brócolis", "legume", "hortifruti"], vezesVendido: 80 },
  { id: "prod_095", nome: "Melancia Pedaço", descricao: "Pedaço de melancia doce e refrescante.", categoria: "hortifruti", preco: 5.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_095"), imagemThumb: getImageUrl("prod_095"), estoque: 15, estoqueMinimo: 3, unidade: "unidade", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 95, tags: ["melancia", "fruta", "hortifruti"], vezesVendido: 70 },
  { id: "prod_096", nome: "Abacaxi", descricao: "Abacaxi pérola maduro.", categoria: "hortifruti", preco: 8.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_096"), imagemThumb: getImageUrl("prod_096"), estoque: 20, estoqueMinimo: 5, unidade: "unidade", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 96, tags: ["abacaxi", "fruta", "hortifruti"], vezesVendido: 95 },
  { id: "prod_097", nome: "Couve Manteiga Maço", descricao: "Maço de couve manteiga fresca.", categoria: "hortifruti", preco: 3.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_097"), imagemThumb: getImageUrl("prod_097"), estoque: 30, estoqueMinimo: 10, unidade: "maço", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 97, tags: ["couve", "verdura", "hortifruti"], vezesVendido: 120 },
  { id: "prod_098", nome: "Manga Tommy", descricao: "Manga tommy madura.", categoria: "hortifruti", preco: 3.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_098"), imagemThumb: getImageUrl("prod_098"), estoque: 25, estoqueMinimo: 5, unidade: "unidade", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 98, tags: ["manga", "fruta", "hortifruti"], vezesVendido: 85 },
  { id: "prod_099", nome: "Batata Doce", descricao: "Batata doce, ótima para dietas.", categoria: "hortifruti", preco: 6.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_099"), imagemThumb: getImageUrl("prod_099"), estoque: 30, estoqueMinimo: 8, unidade: "kg", peso: "1kg", marca: "Hortifruti Luzia", ativo: true, destaque: false, ordem: 99, tags: ["batata doce", "hortifruti", "fit"], vezesVendido: 110 },
  { id: "prod_100", nome: "Ovo de Codorna", descricao: "Ovos de codorna em conserva.", categoria: "hortifruti", preco: 9.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_100"), imagemThumb: getImageUrl("prod_100"), estoque: 40, estoqueMinimo: 10, unidade: "pote", peso: "30un", marca: "Conserva", ativo: true, destaque: false, ordem: 100, tags: ["ovo", "codorna", "conserva"], vezesVendido: 90 },

  // Novos produtos - Bebidas
  { id: "prod_101", nome: "Refrigerante Guaraná Antarctica", descricao: "O guaraná original do Brasil.", categoria: "bebidas", preco: 8.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_101"), imagemThumb: getImageUrl("prod_101"), estoque: 50, estoqueMinimo: 15, unidade: "garrafa", peso: "2L", marca: "Antarctica", ativo: true, destaque: false, ordem: 101, tags: ["refrigerante", "guaraná", "bebidas"], vezesVendido: 250 },
  { id: "prod_102", nome: "Suco de Laranja Del Valle", descricao: "Suco de laranja 100% fruta.", categoria: "bebidas", preco: 9.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_102"), imagemThumb: getImageUrl("prod_102"), estoque: 40, estoqueMinimo: 10, unidade: "caixa", peso: "1L", marca: "Del Valle", ativo: true, destaque: false, ordem: 102, tags: ["suco", "laranja", "bebidas"], vezesVendido: 180 },
  { id: "prod_103", nome: "Água Tônica Schweppes", descricao: "Água tônica para drinks.", categoria: "bebidas", preco: 4.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_103"), imagemThumb: getImageUrl("prod_103"), estoque: 60, estoqueMinimo: 15, unidade: "lata", peso: "350ml", marca: "Schweppes", ativo: true, destaque: false, ordem: 103, tags: ["tônica", "drink", "bebidas"], vezesVendido: 120 },
  { id: "prod_104", nome: "Vinho Tinto Concha y Toro", descricao: "Vinho tinto chileno, Cabernet Sauvignon.", categoria: "bebidas", preco: 39.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_104"), imagemThumb: getImageUrl("prod_104"), estoque: 20, estoqueMinimo: 5, unidade: "garrafa", peso: "750ml", marca: "Concha y Toro", ativo: true, destaque: false, ordem: 104, tags: ["vinho", "tinto", "bebidas"], vezesVendido: 70 },
  { id: "prod_105", nome: "Energético Red Bull", descricao: "Bebida energética para dar um gás.", categoria: "bebidas", preco: 9.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_105"), imagemThumb: getImageUrl("prod_105"), estoque: 50, estoqueMinimo: 10, unidade: "lata", peso: "250ml", marca: "Red Bull", ativo: true, destaque: false, ordem: 105, tags: ["energético", "red bull", "bebidas"], vezesVendido: 200 },
  { id: "prod_106", nome: "Cerveja Skol", descricao: "Cerveja pilsen, a que desce redondo.", categoria: "bebidas", preco: 3.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_106"), imagemThumb: getImageUrl("prod_106"), estoque: 100, estoqueMinimo: 30, unidade: "lata", peso: "350ml", marca: "Skol", ativo: true, destaque: false, ordem: 106, tags: ["cerveja", "skol", "bebidas"], vezesVendido: 300 },
  { id: "prod_107", nome: "Suco de Uva Integral", descricao: "Suco de uva tinto integral, sem adição de açúcar.", categoria: "bebidas", preco: 18.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_107"), imagemThumb: getImageUrl("prod_107"), estoque: 30, estoqueMinimo: 8, unidade: "garrafa", peso: "1.5L", marca: "Aurora", ativo: true, destaque: false, ordem: 107, tags: ["suco", "uva", "integral"], vezesVendido: 100 },
  { id: "prod_108", nome: "Água de Coco", descricao: "Água de coco para se refrescar.", categoria: "bebidas", preco: 11.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_108"), imagemThumb: getImageUrl("prod_108"), estoque: 40, estoqueMinimo: 10, unidade: "caixa", peso: "1L", marca: "Sococo", ativo: true, destaque: false, ordem: 108, tags: ["água de coco", "bebidas"], vezesVendido: 150 },
  { id: "prod_109", nome: "Refrigerante Fanta Laranja", descricao: "Refrigerante sabor laranja.", categoria: "bebidas", preco: 8.20, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_109"), imagemThumb: getImageUrl("prod_109"), estoque: 45, estoqueMinimo: 10, unidade: "garrafa", peso: "2L", marca: "Fanta", ativo: true, destaque: false, ordem: 109, tags: ["refrigerante", "fanta", "bebidas"], vezesVendido: 170 },
  { id: "prod_110", nome: "Vodka Smirnoff", descricao: "Vodka tridestilada.", categoria: "bebidas", preco: 45.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_110"), imagemThumb: getImageUrl("prod_110"), estoque: 15, estoqueMinimo: 4, unidade: "garrafa", peso: "998ml", marca: "Smirnoff", ativo: true, destaque: false, ordem: 110, tags: ["vodka", "destilado", "bebidas"], vezesVendido: 50 },
  { id: "prod_111", nome: "Cachaça 51", descricao: "A cachaça do Brasil.", categoria: "bebidas", preco: 18.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_111"), imagemThumb: getImageUrl("prod_111"), estoque: 25, estoqueMinimo: 5, unidade: "garrafa", peso: "965ml", marca: "51", ativo: true, destaque: false, ordem: 111, tags: ["cachaça", "destilado", "bebidas"], vezesVendido: 80 },
  { id: "prod_112", nome: "Chá Mate Leão", descricao: "Chá mate gelado, pronto para beber.", categoria: "bebidas", preco: 7.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_112"), imagemThumb: getImageUrl("prod_112"), estoque: 35, estoqueMinimo: 10, unidade: "garrafa", peso: "1.5L", marca: "Leão", ativo: true, destaque: false, ordem: 112, tags: ["chá", "mate", "bebidas"], vezesVendido: 130 },
  { id: "prod_113", nome: "Cerveja Brahma Duplo Malte", descricao: "Cerveja com dois tipos de malte.", categoria: "bebidas", preco: 4.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_113"), imagemThumb: getImageUrl("prod_113"), estoque: 80, estoqueMinimo: 20, unidade: "lata", peso: "350ml", marca: "Brahma", ativo: true, destaque: false, ordem: 113, tags: ["cerveja", "brahma", "bebidas"], vezesVendido: 220 },
  { id: "prod_114", nome: "Gim Gordon's", descricao: "London dry gin.", categoria: "bebidas", preco: 65.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_114"), imagemThumb: getImageUrl("prod_114"), estoque: 10, estoqueMinimo: 2, unidade: "garrafa", peso: "750ml", marca: "Gordon's", ativo: true, destaque: false, ordem: 114, tags: ["gim", "destilado", "bebidas"], vezesVendido: 40 },
  { id: "prod_115", nome: "Achocolatado Toddy", descricao: "Achocolatado em pó para leite.", categoria: "bebidas", preco: 9.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_115"), imagemThumb: getImageUrl("prod_115"), estoque: 50, estoqueMinimo: 15, unidade: "pote", peso: "370g", marca: "Toddy", ativo: true, destaque: false, ordem: 115, tags: ["achocolatado", "toddy", "bebidas"], vezesVendido: 190 },

  // Novos produtos - Doces e Biscoitos
  { id: "prod_116", nome: "Biscoito Recheado Oreo", descricao: "O biscoito recheado mais famoso do mundo.", categoria: "doces", preco: 4.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_116"), imagemThumb: getImageUrl("prod_116"), estoque: 80, estoqueMinimo: 20, unidade: "pacote", peso: "90g", marca: "Oreo", ativo: true, destaque: false, ordem: 116, tags: ["biscoito", "oreo", "doce"], vezesVendido: 320 },
  { id: "prod_117", nome: "Chocolate Bis Xtra", descricao: "Wafer com chocolate ao leite.", categoria: "doces", preco: 3.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_117"), imagemThumb: getImageUrl("prod_117"), estoque: 100, estoqueMinimo: 30, unidade: "unidade", peso: "45g", marca: "Lacta", ativo: true, destaque: false, ordem: 117, tags: ["chocolate", "bis", "doce"], vezesVendido: 400 },
  { id: "prod_118", nome: "Salgadinho Cheetos Onda", descricao: "Salgadinho de milho sabor requeijão.", categoria: "doces", preco: 8.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_118"), imagemThumb: getImageUrl("prod_118"), estoque: 60, estoqueMinimo: 15, unidade: "pacote", peso: "140g", marca: "Cheetos", ativo: true, destaque: false, ordem: 118, tags: ["salgadinho", "cheetos"], vezesVendido: 200 },
  { id: "prod_119", nome: "Bala Halls Menta", descricao: "Balas de menta extra forte.", categoria: "doces", preco: 2.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_119"), imagemThumb: getImageUrl("prod_119"), estoque: 120, estoqueMinimo: 30, unidade: "unidade", peso: "28g", marca: "Halls", ativo: true, destaque: false, ordem: 119, tags: ["bala", "halls", "doce"], vezesVendido: 280 },
  { id: "prod_120", nome: "Paçoca", descricao: "Doce de amendoim tradicional.", categoria: "doces", preco: 1.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_120"), imagemThumb: getImageUrl("prod_120"), estoque: 150, estoqueMinimo: 40, unidade: "unidade", peso: "20g", marca: "Paçoquita", ativo: true, destaque: false, ordem: 120, tags: ["paçoca", "doce", "amendoim"], vezesVendido: 500 },
  { id: "prod_121", nome: "Goiabada Cascão", descricao: "Goiabada cremosa tipo cascão.", categoria: "doces", preco: 9.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_121"), imagemThumb: getImageUrl("prod_121"), estoque: 40, estoqueMinimo: 10, unidade: "pote", peso: "300g", marca: "Predilecta", ativo: true, destaque: false, ordem: 121, tags: ["goiabada", "doce"], vezesVendido: 100 },
  { id: "prod_122", nome: "Chiclete Trident Menta", descricao: "Chiclete sem açúcar sabor menta.", categoria: "doces", preco: 2.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_122"), imagemThumb: getImageUrl("prod_122"), estoque: 90, estoqueMinimo: 25, unidade: "unidade", peso: "8g", marca: "Trident", ativo: true, destaque: false, ordem: 122, tags: ["chiclete", "trident", "doce"], vezesVendido: 260 },
  { id: "prod_123", nome: "Biscoito Polvilho", descricao: "Biscoito de polvilho salgado.", categoria: "doces", preco: 4.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_123"), imagemThumb: getImageUrl("prod_123"), estoque: 70, estoqueMinimo: 20, unidade: "pacote", peso: "100g", marca: "Globo", ativo: true, destaque: false, ordem: 123, tags: ["biscoito", "polvilho", "salgado"], vezesVendido: 150 },
  { id: "prod_124", nome: "Gelatina em Pó Royal Morango", descricao: "Gelatina para sobremesa sabor morango.", categoria: "doces", preco: 2.20, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_124"), imagemThumb: getImageUrl("prod_124"), estoque: 80, estoqueMinimo: 20, unidade: "caixa", peso: "25g", marca: "Royal", ativo: true, destaque: false, ordem: 124, tags: ["gelatina", "royal", "sobremesa"], vezesVendido: 180 },
  { id: "prod_125", nome: "Amendoim Japonês Yoki", descricao: "Amendoim torrado e salgado.", categoria: "doces", preco: 6.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_125"), imagemThumb: getImageUrl("prod_125"), estoque: 60, estoqueMinimo: 15, unidade: "pacote", peso: "150g", marca: "Yoki", ativo: true, destaque: false, ordem: 125, tags: ["amendoim", "japonês", "petisco"], vezesVendido: 140 },
  { id: "prod_126", nome: "Pudim em Pó Dr. Oetker", descricao: "Mistura para pudim sabor baunilha.", categoria: "doces", preco: 3.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_126"), imagemThumb: getImageUrl("prod_126"), estoque: 50, estoqueMinimo: 10, unidade: "caixa", peso: "50g", marca: "Dr. Oetker", ativo: true, destaque: false, ordem: 126, tags: ["pudim", "sobremesa"], vezesVendido: 110 },
  { id: "prod_127", nome: "Chocolate em Pó Dois Frades", descricao: "Chocolate em pó 50% cacau.", categoria: "doces", preco: 11.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_127"), imagemThumb: getImageUrl("prod_127"), estoque: 40, estoqueMinimo: 10, unidade: "caixa", peso: "200g", marca: "Nestlé", ativo: true, destaque: false, ordem: 127, tags: ["chocolate", "cacau", "doce"], vezesVendido: 160 },
  { id: "prod_128", nome: "Batata Pringles Original", descricao: "Batatas fritas em lata.", categoria: "doces", preco: 14.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_128"), imagemThumb: getImageUrl("prod_128"), estoque: 30, estoqueMinimo: 8, unidade: "lata", peso: "114g", marca: "Pringles", ativo: true, destaque: false, ordem: 128, tags: ["batata", "pringles", "salgadinho"], vezesVendido: 190 },
  { id: "prod_129", nome: "Biscoito Cream Cracker", descricao: "Biscoito água e sal.", categoria: "doces", preco: 3.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_129"), imagemThumb: getImageUrl("prod_129"), estoque: 70, estoqueMinimo: 20, unidade: "pacote", peso: "200g", marca: "Marilan", ativo: true, destaque: false, ordem: 129, tags: ["biscoito", "cream cracker"], vezesVendido: 170 },
  { id: "prod_130", nome: "Marshmallow Fini", descricao: "Marshmallows macios e doces.", categoria: "doces", preco: 10.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_130"), imagemThumb: getImageUrl("prod_130"), estoque: 35, estoqueMinimo: 10, unidade: "pacote", peso: "250g", marca: "Fini", ativo: true, destaque: false, ordem: 130, tags: ["marshmallow", "fini", "doce"], vezesVendido: 90 },

  // Novos produtos - Limpeza
  { id: "prod_131", nome: "Amaciante Downy", descricao: "Amaciante concentrado, perfume duradouro.", categoria: "limpeza", preco: 18.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_131"), imagemThumb: getImageUrl("prod_131"), estoque: 40, estoqueMinimo: 10, unidade: "garrafa", peso: "500ml", marca: "Downy", ativo: true, destaque: false, ordem: 131, tags: ["amaciante", "downy", "limpeza"], vezesVendido: 150 },
  { id: "prod_132", nome: "Desinfetante Pinho Sol", descricao: "Desinfetante para uso geral.", categoria: "limpeza", preco: 7.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_132"), imagemThumb: getImageUrl("prod_132"), estoque: 60, estoqueMinimo: 15, unidade: "garrafa", peso: "500ml", marca: "Pinho Sol", ativo: true, destaque: false, ordem: 132, tags: ["desinfetante", "limpeza"], vezesVendido: 180 },
  { id: "prod_133", nome: "Esponja de Aço Bombril", descricao: "Lã de aço para limpeza pesada.", categoria: "limpeza", preco: 2.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_133"), imagemThumb: getImageUrl("prod_133"), estoque: 100, estoqueMinimo: 30, unidade: "unidade", marca: "Bombril", ativo: true, destaque: false, ordem: 133, tags: ["esponja", "bombril", "limpeza"], vezesVendido: 300 },
  { id: "prod_134", nome: "Saco de Lixo", descricao: "Sacos de lixo reforçados.", categoria: "limpeza", preco: 9.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_134"), imagemThumb: getImageUrl("prod_134"), estoque: 50, estoqueMinimo: 15, unidade: "pacote", peso: "50L 20un", marca: "Embalixo", ativo: true, destaque: false, ordem: 134, tags: ["saco de lixo", "limpeza"], vezesVendido: 140 },
  { id: "prod_135", nome: "Limpador Multiuso Veja", descricao: "Limpador para todas as superfícies.", categoria: "limpeza", preco: 6.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_135"), imagemThumb: getImageUrl("prod_135"), estoque: 70, estoqueMinimo: 20, unidade: "garrafa", peso: "500ml", marca: "Veja", ativo: true, destaque: false, ordem: 135, tags: ["multiuso", "veja", "limpeza"], vezesVendido: 220 },
  { id: "prod_136", nome: "Tira Manchas Vanish", descricao: "Removedor de manchas para tecidos.", categoria: "limpeza", preco: 22.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_136"), imagemThumb: getImageUrl("prod_136"), estoque: 30, estoqueMinimo: 8, unidade: "pote", peso: "500g", marca: "Vanish", ativo: true, destaque: false, ordem: 136, tags: ["tira manchas", "vanish", "limpeza"], vezesVendido: 100 },
  { id: "prod_137", nome: "Inseticida Raid", descricao: "Proteção contra insetos voadores.", categoria: "limpeza", preco: 12.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_137"), imagemThumb: getImageUrl("prod_137"), estoque: 40, estoqueMinimo: 10, unidade: "lata", peso: "300ml", marca: "Raid", ativo: true, destaque: false, ordem: 137, tags: ["inseticida", "raid", "limpeza"], vezesVendido: 90 },
  { id: "prod_138", nome: "Álcool em Gel 70%", descricao: "Álcool em gel para higienização das mãos.", categoria: "limpeza", preco: 10.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_138"), imagemThumb: getImageUrl("prod_138"), estoque: 60, estoqueMinimo: 15, unidade: "garrafa", peso: "500ml", marca: "Asseptgel", ativo: true, destaque: false, ordem: 138, tags: ["álcool", "higiene", "limpeza"], vezesVendido: 160 },
  { id: "prod_139", nome: "Pano de Chão", descricao: "Pano de chão de alta absorção.", categoria: "limpeza", preco: 5.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_139"), imagemThumb: getImageUrl("prod_139"), estoque: 80, estoqueMinimo: 20, unidade: "unidade", marca: "Superpro", ativo: true, destaque: false, ordem: 139, tags: ["pano", "limpeza"], vezesVendido: 130 },
  { id: "prod_140", nome: "Limpa Vidros Limpol", descricao: "Limpa vidros e espelhos sem deixar manchas.", categoria: "limpeza", preco: 8.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_140"), imagemThumb: getImageUrl("prod_140"), estoque: 45, estoqueMinimo: 10, unidade: "garrafa", peso: "500ml", marca: "Limpol", ativo: true, destaque: false, ordem: 140, tags: ["limpa vidros", "limpeza"], vezesVendido: 110 },
  { id: "prod_141", nome: "Papel Toalha", descricao: "Rolo de papel toalha multiuso.", categoria: "limpeza", preco: 7.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_141"), imagemThumb: getImageUrl("prod_141"), estoque: 70, estoqueMinimo: 20, unidade: "pacote", peso: "2un", marca: "Snob", ativo: true, destaque: false, ordem: 141, tags: ["papel toalha", "limpeza"], vezesVendido: 200 },
  { id: "prod_142", nome: "Sabão em Barra Ypê", descricao: "Sabão em barra neutro para louças e roupas.", categoria: "limpeza", preco: 9.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_142"), imagemThumb: getImageUrl("prod_142"), estoque: 60, estoqueMinimo: 15, unidade: "pacote", peso: "5un", marca: "Ypê", ativo: true, destaque: false, ordem: 142, tags: ["sabão", "ypê", "limpeza"], vezesVendido: 190 },
  { id: "prod_143", nome: "Luvas de Borracha", descricao: "Par de luvas de borracha para limpeza, tamanho M.", categoria: "limpeza", preco: 6.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_143"), imagemThumb: getImageUrl("prod_143"), estoque: 50, estoqueMinimo: 10, unidade: "par", peso: "M", marca: "Limppano", ativo: true, destaque: false, ordem: 143, tags: ["luvas", "limpeza"], vezesVendido: 80 },
  { id: "prod_144", nome: "Desengordurante Cif", descricao: "Desengordurante para cozinha.", categoria: "limpeza", preco: 11.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_144"), imagemThumb: getImageUrl("prod_144"), estoque: 40, estoqueMinimo: 10, unidade: "garrafa", peso: "500ml", marca: "Cif", ativo: true, destaque: false, ordem: 144, tags: ["desengordurante", "cif", "limpeza"], vezesVendido: 120 },
  { id: "prod_145", nome: "Rodo Mágico", descricao: "Rodo com esponja que absorve líquidos.", categoria: "limpeza", preco: 35.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_145"), imagemThumb: getImageUrl("prod_145"), estoque: 20, estoqueMinimo: 5, unidade: "unidade", marca: "Superclean", ativo: true, destaque: false, ordem: 145, tags: ["rodo", "limpeza"], vezesVendido: 60 },

  // Novos produtos - Higiene Pessoal
  { id: "prod_146", nome: "Sabonete Dove Original", descricao: "Sabonete com 1/4 de creme hidratante.", categoria: "higiene", preco: 3.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_146"), imagemThumb: getImageUrl("prod_146"), estoque: 100, estoqueMinimo: 25, unidade: "unidade", peso: "90g", marca: "Dove", ativo: true, destaque: false, ordem: 146, tags: ["sabonete", "dove", "higiene"], vezesVendido: 350 },
  { id: "prod_147", nome: "Shampoo Seda Ceramidas", descricao: "Shampoo para dar brilho e força aos cabelos.", categoria: "higiene", preco: 12.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_147"), imagemThumb: getImageUrl("prod_147"), estoque: 50, estoqueMinimo: 10, unidade: "frasco", peso: "325ml", marca: "Seda", ativo: true, destaque: false, ordem: 147, tags: ["shampoo", "seda", "higiene"], vezesVendido: 200 },
  { id: "prod_148", nome: "Creme Dental Colgate Total 12", descricao: "Creme dental com proteção completa por 12 horas.", categoria: "higiene", preco: 6.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_148"), imagemThumb: getImageUrl("prod_148"), estoque: 90, estoqueMinimo: 20, unidade: "unidade", peso: "90g", marca: "Colgate", ativo: true, destaque: false, ordem: 148, tags: ["creme dental", "colgate", "higiene"], vezesVendido: 400 },
  { id: "prod_149", nome: "Desodorante Aerosol Rexona", descricao: "Antitranspirante com 48h de proteção.", categoria: "higiene", preco: 15.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_149"), imagemThumb: getImageUrl("prod_149"), estoque: 70, estoqueMinimo: 15, unidade: "unidade", peso: "150ml", marca: "Rexona", ativo: true, destaque: false, ordem: 149, tags: ["desodorante", "rexona", "higiene"], vezesVendido: 300 },
  { id: "prod_150", nome: "Papel Higiênico Neve", descricao: "Papel higiênico folha dupla, toque de seda.", categoria: "higiene", preco: 8.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_150"), imagemThumb: getImageUrl("prod_150"), estoque: 80, estoqueMinimo: 20, unidade: "pacote", peso: "4un", marca: "Neve", ativo: true, destaque: false, ordem: 150, tags: ["papel higiênico", "neve", "higiene"], vezesVendido: 280 },
  { id: "prod_151", nome: "Fio Dental Johnson & Johnson", descricao: "Fio dental para higiene bucal completa.", categoria: "higiene", preco: 9.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_151"), imagemThumb: getImageUrl("prod_151"), estoque: 60, estoqueMinimo: 15, unidade: "unidade", peso: "50m", marca: "Johnson & Johnson", ativo: true, destaque: false, ordem: 151, tags: ["fio dental", "higiene"], vezesVendido: 150 },
  { id: "prod_152", nome: "Absorvente Always", descricao: "Absorvente com abas, cobertura seca.", categoria: "higiene", preco: 7.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_152"), imagemThumb: getImageUrl("prod_152"), estoque: 50, estoqueMinimo: 10, unidade: "pacote", peso: "8un", marca: "Always", ativo: true, destaque: false, ordem: 152, tags: ["absorvente", "higiene"], vezesVendido: 120 },
  { id: "prod_153", nome: "Cotonetes Cotonella", descricao: "Hastes flexíveis com pontas de algodão.", categoria: "higiene", preco: 4.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_153"), imagemThumb: getImageUrl("prod_153"), estoque: 70, estoqueMinimo: 20, unidade: "caixa", peso: "75un", marca: "Cotonella", ativo: true, destaque: false, ordem: 153, tags: ["cotonetes", "higiene"], vezesVendido: 180 },
  { id: "prod_154", nome: "Protetor Solar Nivea Sun", descricao: "Protetor solar para corpo e rosto.", categoria: "higiene", preco: 45.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_154"), imagemThumb: getImageUrl("prod_154"), estoque: 30, estoqueMinimo: 5, unidade: "frasco", peso: "FPS 50 200ml", marca: "Nivea", ativo: true, destaque: false, ordem: 154, tags: ["protetor solar", "nivea", "higiene"], vezesVendido: 100 },
  { id: "prod_155", nome: "Condicionador Seda Ceramidas", descricao: "Condicionador para dar brilho e força.", categoria: "higiene", preco: 13.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_155"), imagemThumb: getImageUrl("prod_155"), estoque: 45, estoqueMinimo: 10, unidade: "frasco", peso: "325ml", marca: "Seda", ativo: true, destaque: false, ordem: 155, tags: ["condicionador", "seda", "higiene"], vezesVendido: 190 },
  { id: "prod_156", nome: "Aparelho de Barbear Gillette Mach3", descricao: "Aparelho de barbear com 3 lâminas.", categoria: "higiene", preco: 25.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_156"), imagemThumb: getImageUrl("prod_156"), estoque: 40, estoqueMinimo: 10, unidade: "unidade", marca: "Gillette", ativo: true, destaque: false, ordem: 156, tags: ["barbear", "gillette", "higiene"], vezesVendido: 130 },
  { id: "prod_157", nome: "Hidratante Corporal Nivea Milk", descricao: "Loção hidratante para pele seca.", categoria: "higiene", preco: 18.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_157"), imagemThumb: getImageUrl("prod_157"), estoque: 50, estoqueMinimo: 10, unidade: "frasco", peso: "200ml", marca: "Nivea", ativo: true, destaque: false, ordem: 157, tags: ["hidratante", "nivea", "higiene"], vezesVendido: 160 },
  { id: "prod_158", nome: "Fralda Descartável Pampers", descricao: "Fraldas descartáveis para bebês.", categoria: "higiene", preco: 38.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_158"), imagemThumb: getImageUrl("prod_158"), estoque: 30, estoqueMinimo: 8, unidade: "pacote", peso: "M 30un", marca: "Pampers", ativo: true, destaque: false, ordem: 158, tags: ["fralda", "pampers", "bebê"], vezesVendido: 110 },
  { id: "prod_159", nome: "Enxaguante Bucal Listerine", descricao: "Antisséptico bucal para hálito fresco.", categoria: "higiene", preco: 22.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_159"), imagemThumb: getImageUrl("prod_159"), estoque: 35, estoqueMinimo: 10, unidade: "frasco", peso: "500ml", marca: "Listerine", ativo: true, destaque: false, ordem: 159, tags: ["enxaguante", "listerine", "higiene"], vezesVendido: 140 },
  { id: "prod_160", nome: "Talco para Pés Tenys Pé Baruel", descricao: "Talco antisséptico para os pés.", categoria: "higiene", preco: 14.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_160"), imagemThumb: getImageUrl("prod_160"), estoque: 40, estoqueMinimo: 10, unidade: "frasco", peso: "100g", marca: "Baruel", ativo: true, destaque: false, ordem: 160, tags: ["talco", "pés", "higiene"], vezesVendido: 90 },

  // Novos produtos - Mercearia
  { id: "prod_161", nome: "Azeite de Oliva Extra Virgem Gallo", descricao: "Azeite extra virgem para temperar e finalizar pratos.", categoria: "mercearia", preco: 35.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_161"), imagemThumb: getImageUrl("prod_161"), estoque: 40, estoqueMinimo: 10, unidade: "garrafa", peso: "500ml", marca: "Gallo", ativo: true, destaque: false, ordem: 161, tags: ["azeite", "gallo", "mercearia"], vezesVendido: 180 },
  { id: "prod_162", nome: "Molho de Tomate Tradicional Heinz", descricao: "Molho de tomate pronto para massas.", categoria: "mercearia", preco: 5.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_162"), imagemThumb: getImageUrl("prod_162"), estoque: 80, estoqueMinimo: 20, unidade: "sachê", peso: "300g", marca: "Heinz", ativo: true, destaque: false, ordem: 162, tags: ["molho", "tomate", "heinz"], vezesVendido: 250 },
  { id: "prod_163", nome: "Maionese Hellmann's", descricao: "A verdadeira maionese.", categoria: "mercearia", preco: 11.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_163"), imagemThumb: getImageUrl("prod_163"), estoque: 60, estoqueMinimo: 15, unidade: "pote", peso: "500g", marca: "Hellmann's", ativo: true, destaque: false, ordem: 163, tags: ["maionese", "hellmanns", "mercearia"], vezesVendido: 220 },
  { id: "prod_164", nome: "Café em Pó Pilão", descricao: "Café torrado e moído, o café forte do Brasil.", categoria: "mercearia", preco: 18.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_164"), imagemThumb: getImageUrl("prod_164"), estoque: 50, estoqueMinimo: 15, unidade: "pacote", peso: "500g", marca: "Pilão", ativo: true, destaque: false, ordem: 164, tags: ["café", "pilão", "mercearia"], vezesVendido: 280 },
  { id: "prod_165", nome: "Atum Sólido em Óleo Gomes da Costa", descricao: "Atum em pedaços conservado em óleo.", categoria: "mercearia", preco: 9.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_165"), imagemThumb: getImageUrl("prod_165"), estoque: 45, estoqueMinimo: 10, unidade: "lata", peso: "170g", marca: "Gomes da Costa", ativo: true, destaque: false, ordem: 165, tags: ["atum", "peixe", "conserva"], vezesVendido: 130 },
  { id: "prod_166", nome: "Vinagre de Álcool Castelo", descricao: "Vinagre de álcool para tempero e limpeza.", categoria: "mercearia", preco: 4.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_166"), imagemThumb: getImageUrl("prod_166"), estoque: 70, estoqueMinimo: 20, unidade: "garrafa", peso: "750ml", marca: "Castelo", ativo: true, destaque: false, ordem: 166, tags: ["vinagre", "castelo", "mercearia"], vezesVendido: 190 },
  { id: "prod_167", nome: "Ketchup Heinz", descricao: "O ketchup mais famoso do mundo.", categoria: "mercearia", preco: 10.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_167"), imagemThumb: getImageUrl("prod_167"), estoque: 60, estoqueMinimo: 15, unidade: "garrafa", peso: "397g", marca: "Heinz", ativo: true, destaque: false, ordem: 167, tags: ["ketchup", "heinz", "mercearia"], vezesVendido: 240 },
  { id: "prod_168", nome: "Macarrão Espaguete Barilla", descricao: "Macarrão de sêmola de grano duro.", categoria: "mercearia", preco: 8.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_168"), imagemThumb: getImageUrl("prod_168"), estoque: 55, estoqueMinimo: 15, unidade: "pacote", peso: "500g", marca: "Barilla", ativo: true, destaque: false, ordem: 168, tags: ["macarrão", "barilla", "massa"], vezesVendido: 200 },
  { id: "prod_169", nome: "Mostarda Hellmann's", descricao: "Mostarda amarela para lanches.", categoria: "mercearia", preco: 7.20, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_169"), imagemThumb: getImageUrl("prod_169"), estoque: 50, estoqueMinimo: 10, unidade: "garrafa", peso: "200g", marca: "Hellmann's", ativo: true, destaque: false, ordem: 169, tags: ["mostarda", "hellmanns", "mercearia"], vezesVendido: 150 },
  { id: "prod_170", nome: "Caldo de Galinha Knorr", descricao: "Caldo de galinha em cubos.", categoria: "mercearia", preco: 3.50, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_170"), imagemThumb: getImageUrl("prod_170"), estoque: 80, estoqueMinimo: 20, unidade: "caixa", peso: "6un", marca: "Knorr", ativo: true, destaque: false, ordem: 170, tags: ["caldo", "knorr", "tempero"], vezesVendido: 260 },
  { id: "prod_171", nome: "Geleia de Morango Queensberry", descricao: "Geleia de morango com pedaços da fruta.", categoria: "mercearia", preco: 15.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_171"), imagemThumb: getImageUrl("prod_171"), estoque: 30, estoqueMinimo: 5, unidade: "pote", peso: "320g", marca: "Queensberry", ativo: true, destaque: false, ordem: 171, tags: ["geleia", "morango", "doce"], vezesVendido: 90 },
  { id: "prod_172", nome: "Palmito Pupunha em Conserva", descricao: "Palmito pupunha em toletes.", categoria: "mercearia", preco: 19.90, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_172"), imagemThumb: getImageUrl("prod_172"), estoque: 25, estoqueMinimo: 5, unidade: "pote", peso: "300g", marca: "Do Campo", ativo: true, destaque: false, ordem: 172, tags: ["palmito", "conserva", "mercearia"], vezesVendido: 70 },
  { id: "prod_173", nome: "Sardinha em Óleo Coqueiro", descricao: "Sardinha em lata conservada em óleo.", categoria: "mercearia", preco: 5.80, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_173"), imagemThumb: getImageUrl("prod_173"), estoque: 60, estoqueMinimo: 15, unidade: "lata", peso: "125g", marca: "Coqueiro", ativo: true, destaque: false, ordem: 173, tags: ["sardinha", "peixe", "conserva"], vezesVendido: 140 },
  { id: "prod_174", nome: "Creme de Avelã Nutella", descricao: "O original creme de avelã com cacau.", categoria: "mercearia", preco: 12.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_174"), imagemThumb: getImageUrl("prod_174"), estoque: 40, estoqueMinimo: 10, unidade: "pote", peso: "140g", marca: "Nutella", ativo: true, destaque: false, ordem: 174, tags: ["nutella", "creme de avelã", "doce"], vezesVendido: 210 },
  { id: "prod_175", nome: "Filtro de Café de Papel Melitta", descricao: "Filtro de papel para café, 30 unidades.", categoria: "mercearia", preco: 6.00, precoAntigo: null, emPromocao: false, imagemURL: getImageUrl("prod_175"), imagemThumb: getImageUrl("prod_175"), estoque: 50, estoqueMinimo: 10, unidade: "caixa", peso: "103", marca: "Melitta", ativo: true, destaque: false, ordem: 175, tags: ["filtro", "café", "melitta"], vezesVendido: 170 }
];


export const categories: Category[] = [
  { id: "hortifruti", nome: "Hortifruti", icone: "🥬", cor: "#28a745", ordem: 1, ativa: true, descricao: "Frutas, verduras e legumes frescos" },
  { id: "carnes", nome: "Carnes e Aves", icone: "🍖", cor: "#e63946", ordem: 2, ativa: true, descricao: "Carnes bovinas, suínas e de aves" },
  { id: "laticinios", nome: "Laticínios e Frios", icone: "🧀", cor: "#4a6fa5", ordem: 3, ativa: true, descricao: "Leite, queijos, iogurtes e presuntos" },
  { id: "padaria", nome: "Padaria", icone: "🍞", cor: "#d4a373", ordem: 4, ativa: true, descricao: "Pães frescos, bolos e salgados" },
  { id: "graos", nome: "Grãos e Cereais", icone: "🌾", cor: "#f5b841", ordem: 5, ativa: true, descricao: "Arroz, feijão, milho e mais" },
  { id: "limpeza", nome: "Limpeza", icone: "🧹", cor: "#ff9800", ordem: 6, ativa: true, descricao: "Produtos para limpeza da casa e roupas" },
  { id: "higiene", nome: "Higiene Pessoal", icone: "🧼", cor: "#90e0ef", ordem: 7, ativa: true, descricao: "Sabonetes, shampoos e cuidados pessoais" },
  { id: "doces", nome: "Doces e Biscoitos", icone: "🍫", cor: "#e5989b", ordem: 8, ativa: true, descricao: "Chocolates, balas, biscoitos e sobremesas" },
  { id: "mercearia", nome: "Mercearia", icone: "🥫", cor: "#6c757d", ordem: 9, ativa: true, descricao: "Óleos, enlatados, temperos e mais" },
  { id: "bebidas", nome: "Bebidas", icone: "🥤", cor: "#00b4d8", ordem: 10, ativa: true, descricao: "Refrigerantes, sucos, águas e cervejas" },
];

export const banners: Banner[] = [
    { id: "banner_001", titulo: "Promoção Arroz e Feijão", descricao: "Leve o kit e ganhe 15% de desconto", imagemURL: getImageUrl("banner-1"), imagemMobileURL: getImageUrl("banner-1"), link: "/categorias/graos", ordem: 1, ativo: true },
    { id: "banner_002", titulo: "Hortifruti Fresquinho", descricao: "Frutas e verduras direto do produtor", imagemURL: getImageUrl("banner-2"), imagemMobileURL: getImageUrl("banner-2"), link: "/categorias/hortifruti", ordem: 2, ativo: true },
    { id: "banner_003", titulo: "Fim de Semana do Churrasco", descricao: "Os melhores cortes com preços especiais", imagemURL: getImageUrl("banner-3"), imagemMobileURL: getImageUrl("banner-3"), link: "/categorias/carnes", ordem: 3, ativo: true },
];

export const siteConfig: Config = {
  id: "geral",
  whatsappNumero: "5598970066071",
  whatsappMensagem: "Olá! Vim do site Luzia Delivery e gostaria de fazer um pedido.",
  horarioAbertura: "00:00",
  horarioFechamento: "23:59",
  diasFuncionamento: ["seg", "ter", "qua", "qui", "sex", "sab", "dom"],
  taxaEntrega: 3.99,
  pedidoMinimo: 20.00,
  mensagemBanner: "🔥 Frete grátis acima de R$ 100!",
  mensagemRodape: "Entregamos com amor e carinho ❤️",
  lojaAberta: true,
  aceitandoPedidos: true
};
